name = "PowerAnalyses"
uuid = "fee4b835-1841-44f8-82ea-42813857171a"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Distributions = "0.25"
Roots = "1"
julia = "1.6"
